parameters:
  buildArchitecture: 'x64'
jobs:
- job: build_macOS_${{ parameters.buildArchitecture }}
  displayName: Build macOS ${{ parameters.buildArchitecture }}
  condition: succeeded()
  pool:
    type: linux
    isCustom: true
    name: Azure Pipelines
    vmImage: 'macOS-latest'

  variables:
  - name: HOMEBREW_NO_ANALYTICS
    value: 1
  - name: NugetSecurityAnalysisWarningLevel
    value: none
  - group: DotNetPrivateBuildAccess
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
  - name: PowerShellRoot
    value: $(Build.SourcesDirectory)

  steps:
  - checkout: self
    clean: true
    env:
      ob_restore_phase: true # This ensures checkout is done at the beginning of the restore phase

  - template: /.pipelines/templates/SetVersionVariables.yml@self
    parameters:
      ReleaseTagVar: $(ReleaseTagVar)
  - pwsh: |
      # create folder
      sudo mkdir "$(Agent.TempDirectory)/PowerShell"
      # make the current user the owner
      sudo chown $env:USER "$(Agent.TempDirectory)/PowerShell"
    displayName: 'Create $(Agent.TempDirectory)/PowerShell'

    ## We cross compile for arm64, so the arch is always x64
  - template: /.pipelines/templates/install-dotnet.yml@self

  - pwsh: |
      Import-Module $(PowerShellRoot)/build.psm1 -Force
      Start-PSBootstrap -Scenario Package
    displayName: 'Bootstrap VM'
    env:
      __DOTNET_RUNTIME_FEED_KEY: $(RUNTIME_SOURCEFEED_KEY)

  - template: /.pipelines/templates/insert-nuget-config-azfeed.yml@self
    parameters:
      repoRoot: $(PowerShellRoot)
  - pwsh: |
      $env:AzDevOpsFeedPAT2 = '$(powershellPackageReadPat)'
      # Add -SkipReleaseChecks as a mitigation to unblock release.
      # macos-10.15 does not allow creating a folder under root. Hence, moving the folder.

      Import-Module ./build.psm1 -Force

      $ReleaseTagParam = @{}

      if ($env:RELEASETAGVAR) {
        $ReleaseTagParam['ReleaseTag'] = $env:RELEASETAGVAR
      }

      Start-PSBuild -Runtime 'osx-${{ parameters.buildArchitecture }}' -Configuration Release -PSModuleRestore -Clean -Output $(OB_OUTPUTDIRECTORY) @ReleaseTagParam
      $artifactName = "macosBinResults-${{ parameters.buildArchitecture }}"

      $psOptPath = "$(OB_OUTPUTDIRECTORY)/psoptions.json"
      Save-PSOptions -PSOptionsPath $psOptPath

      # Since we are using custom pool for macOS, we need to use artifact.upload to publish the artifacts
      Write-Host "##vso[artifact.upload containerfolder=$artifactName;artifactname=$artifactName]$(OB_OUTPUTDIRECTORY)"

      $env:AzDevOpsFeedPAT2 = $null
    displayName: 'Build'
    env:
      __DOTNET_RUNTIME_FEED_KEY: $(RUNTIME_SOURCEFEED_KEY)

  - template: /.pipelines/templates/step/finalize.yml@self

- job: sign_${{ parameters.buildArchitecture }}
  displayName: Sign macOS ${{ parameters.buildArchitecture }}
  condition: succeeded()
  dependsOn: build_macOS_${{ parameters.buildArchitecture }}
  pool:
    type: windows
  variables:
  - name: NugetSecurityAnalysisWarningLevel
    value: none
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
  - name: ob_sdl_codeSignValidation_enabled # This isn't Windows so we're not Authenticode signing
    value: false
  - name: ob_sdl_binskim_enabled # Mach-O binaries, not Windows PE
    value: false
  - name: ob_sdl_credscan_enabled # No source code to scan, build job handles this
    value: false
  - name: ob_sdl_codeql_compiled_enabled
    value: false
  - name: BuildArchitecture
    value: ${{ parameters.buildArchitecture }}

  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: 'macosBinResults-$(BuildArchitecture)'
      path: '$(Pipeline.Workspace)\macosBinResults-$(BuildArchitecture)'
    displayName: Download build

  - pwsh: |
        Get-ChildItem "$(Pipeline.Workspace)\*" -Recurse
    displayName: 'Capture Downloaded Artifacts'
    continueOnError: true

  - pwsh: |
      $binariesPath = "$(Pipeline.Workspace)/macosBinResults-$(BuildArchitecture)"
      $toBeSigned = "$(Pipeline.Workspace)/toBeSigned"
      $null = New-Item -Path $toBeSigned -ItemType Directory -Force
      Write-Verbose -Verbose "Compressing binaries for signing..."
      $zipFile = "$toBeSigned/macosBinResults-$(BuildArchitecture).zip"
      Compress-Archive -Path "$binariesPath/*" -Destination $zipFile
      Write-Verbose -Verbose "Zip file: $zipFile"
    displayName: Compress binaries for signing

  - task: onebranch.pipeline.signing@1
    displayName: 'Apple CodeSign Binaries'
    inputs:
      command: 'sign'
      files_to_sign: 'macosBinResults-*.zip'
      search_root: '$(Pipeline.Workspace)/toBeSigned'
      inline_operation: |
        [
          {
            "KeyCode": "CP-401337-Apple",
            "OperationCode": "MacAppDeveloperSign",
            "ToolName": "sign",
            "ToolVersion": "1.0",
            "Parameters": {
              "Hardening": "--options=runtime"
            }
          }
        ]

  - pwsh: |
      $zipFile = "$(Pipeline.Workspace)/toBeSigned/macosBinResults-$(BuildArchitecture).zip"

      if (-not (Test-Path $(ob_outputDirectory))) {
        $null = New-Item -Path $(ob_outputDirectory) -ItemType Directory
      }

      Expand-Archive -Path $zipFile -DestinationPath $(ob_outputDirectory) -Verbose
    displayName: Expand signed binaries

  - template: /.pipelines/templates/step/finalize.yml@self
